# filters for gmail
# use with jessfraz/gmailfilters

# operators:
#
# from: ...
# list: ...
# to: ...
# deliveredto: ...
# subject: ...
#
# ... OR  ... or {... ...}
# ... AND ... or (... ...)
# "..."                     # exact match
# +...                      # exact match word
# -                         # not
# AROUND <n>
# 
# in:anywhere               # include spam and trash
# category: ...
# label: ...
# has: userlabels nouserlabels
# has: attachment drive document spreadsheet presentation drive youtube
# has: <icon> yellow-star blue-info
# is: starred snoozed unread read chat
# filename: ext file.ext
# size: ... larger: ... smaller: ...
#
# before: ... after: ... older: <date> newer: yyyy/mm/dd
# older_than: <reltime> newer_than: <n>d/m/y
# rfc822msgid: ...


[[Filter]]
    Label = "CATEGORY_PROMOTIONS"
    QueryOr = [
        "from:(*@edm.ibon.com.tw)",
        "from:(*@myotgcard.starbucks.com.tw)",
    ]
    Archive = true
    Read = true

[[Filter]]
    Label = "CATEGORY_SOCIAL"
    QueryOr = [
        "from:(notifications@redditmail.com)",
        "(from:(*@linkedin.com) -from:(security-noreply@linkedin.com))",
    ]
    Archive = true

[[Filter]]
    Label = "Account Security"
    QueryOR = [
        "(password AROUND 5 change)",
        "(login noti)",
        "(account access)",
        "(verify AROUND 3 email)",
        "(security alert)",
        "(new device)",
        "(new login)",
        "(new ip)",
        "(網路銀行登入)",
    ]

[[Filter]]
    Label = "Logging"
    QueryOr = [
        "from:(builds@travis-ci.org)",
    ]
    Archive = true
    Read = true
